/**
 * @warning This file is auto-generated by `generate_registers_map.py` script. Do not edit manually.
 * @file    stm32l476xx_registers.h
 * @author  Jakub Zakrzewski
 * @brief   STM32L476xx hardware register mapping
 * @date    2026-03-09
 *
 * @copyright Copyright (c) 2026
 */

#ifndef __REGISTERS_MAP_H
#define __REGISTERS_MAP_H

#ifdef __cplusplus
extern "C"
{
#endif

#include <stddef.h>
#include <stdint.h>

#define REGISTERS_COUNT 1102

    typedef struct
    {
        const char *name;
        volatile void *address;
        size_t size;
    } register_t;

    extern register_t hwregs[REGISTERS_COUNT];

    void registers_init(void);
    register_t *get_register(const char *name);

#ifdef __cplusplus
}
#endif

#endif /* __REGISTERS_MAP_H */